### ISSUE TITLE
Error Invalid profile 'vs_4_0' Vertex Shader 'VS' must be SM 3.0 or lower

### ISSUE THREAD

**Issue by PodeCaradox** [cpt-max/ShaderTest#1]
Hey,

first of all thanks for your fork. But i have the following error if i build the content with your pipeline tool:
[Edit]
I was just dump and forgot to clone your specific branch, sorry for that.
You can close the issue but maybe someone else also missing it. x)

Platform:OpenGL
![image](https://user-images.githubusercontent.com/5760157/98885642-b24abe00-2492-11eb-82c5-1f62ca2aaf08.png)

The content Pipelinei used to open the ShaderTestGL.mgcb
![image](https://user-images.githubusercontent.com/5760157/98885918-38ff9b00-2493-11eb-97cf-1d6f4fee57d4.png)

with directx it works perfectly, but somehow i get the error on GL platform.
![image](https://user-images.githubusercontent.com/5760157/98885684-c393ca80-2492-11eb-8207-9836926e827c.png)

i cloned your git: https://github.com/cpt-max/MonoGame.git
,after that i updated it with: git submodule update --init
,than i build the pipeline tools in visual studio.
Added the Monogame gl project as reference(MonoGame.Framework.DesktopGL.csproj).
And in the end i opened ShaderTestGL.mgcb from the build of the content pipeline(MonoGame.Tools.Windows.sln) and pressed build.

**Comment by cpt-max** [comment]
I see, you cloned the default branch of my MonoGame fork, which was for DirectX only. I just changed the default branch so it points to the DirectX & OpenGL version. Should make it less likely to clone the wrong branch.
