### ISSUE TITLE
Debugging Shader.

### ISSUE THREAD

**Issue by PodeCaradox** [cpt-max/ShaderTest#2]
Hey CPT-Max,

how did you debug your shader code with OpenGl?
with: 
#define VS_SHADERMODEL vs_5_0
#define PS_SHADERMODEL ps_5_0
#define CS_SHADERMODEL cs_5_0 
i get in RenderDoc the error only opengl 3.2+ context are supported.
I have a amd Card and maybe you can give me some direction i can read how to debug it, because i struggling with a custom approach for Culling in a compute shader

Thank you for advice.

**Comment by cpt-max** [comment]
Hi @PodeCaradox,
RenderDoc works for me with OpenGL, but it requires an OpenGL debug context. Only a debug build will currently create a debug context. You probably tried to debug a release build. Debugging a release build will only work if you change the source of MonoGame.Framework.DesktopGL. You would need to remove the ```#if DEBUG``` in GraphicsContext.SDL.cs
```c#
#if DEBUG
    // create debug context, so we get better error messages (glDebugMessageCallback)
    Sdl.GL.SetAttribute(Sdl.GL.Attribute.ContextFlags, 1); // 1 = SDL_GL_CONTEXT_DEBUG_FLAG
#endif
```

**Comment by PodeCaradox** [comment]
Hi @cpt-max ,
ah thats my Problem, i didnt build with the source Project from you thank you. :)
